version: '3.5'
services:
  #Nginx Service
  # webserver:
  #   image: nginx
  #   container_name: webserver
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "8881:80"
  #     - "443:443"
  #   volumes:
  #     - ./websites/:/usr/share/nginx/html
  #     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - app-network
#MySQL Service
  webserver_db_service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: webserver_db
    restart: unless-stopped
    tty: true
    ports:
      - "1306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_USER: vishva
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysqldata:/var/lib/mysql
    # networks:
    #   - app-network
  # phpmyadmin
  phpmyadmin_service:
    depends_on:
      - webserver_db_service
    image: phpmyadmin/phpmyadmin
    container_name: webserver_db_access
    restart: unless-stopped
    ports:
      - '8882:80'
    links: 
      - webserver_db_service:webserver_db
    environment:
      PMA_HOST: webserver_db
      PMA_PORT: 3306
    # networks:
    #   - app-network
networks: 
  default: 
    external: 
      name: vishva